# Repartitioning runs on Azure Pipelines, because that's where we have SSH
# access to the download server.

name: $(Date:yyyyMMdd).$(Rev:r)

# Do not run automatically
trigger: none


parameters:
- name: SigningCertificate
  displayName: "Code signing certificate"
  type: string
  default: 'PythonSoftwareFoundation'
  values:
  - 'PythonSoftwareFoundation'
  - 'TestSign'
  - 'Unsigned'
- name: Publish
  displayName: "Publish"
  type: boolean
  default: false
- name: SigningDescription
  displayName: "Signature description"
  type: string
  default: '(default)'


variables:
  ${{ if eq(parameters.SigningDescription, '(default)') }}:
    SigningDescription: "PyManager $(Build.BuildNumber)"
  ${{ else }}:
    SigningDescription: ${{ parameters.SigningDescription }}


stages:
- stage: PyManagerIndexPartition
  displayName: 'Repartition PyManager Index'

  jobs:
  - job: Repartition

    pool:
      vmImage: 'windows-latest'

    variables:
    - ${{ if eq(parameters.Publish, 'true') }}:
      - group: PythonOrgPublish
    - ${{ if eq(parameters.SigningCertificate, 'TestSign') }}:
      - group: CPythonTestSign
    - ${{ elseif eq(parameters.SigningCertificate, 'PythonSoftwareFoundation') }}:
      - group: CPythonSign

    steps:
    - checkout: self

    - task: NugetToolInstaller@0
      displayName: 'Install Nuget'

    - powershell: |
        nuget install -o host_python -x -noninteractive python
        Write-Host "##vso[task.prependpath]$(gi host_python\python\tools)"
      displayName: 'Install host Python'
      workingDirectory: $(Build.BinariesDirectory)

    - powershell: |
        cd (mkdir -Force index)
        python "$(Build.SourcesDirectory)\scripts\repartition-index.py" --windows-default
        # Show the report
        cat index-windows.txt
      displayName: 'Repartition index'
      workingDirectory: $(Build.BinariesDirectory)

    - powershell: |
        dir *.json | %{ New-FileCatalog "$($_.Name).cat" -CatalogVersion 2 $_ }
      displayName: 'Create index catalog files'
      workingDirectory: $(Build.BinariesDirectory)\index

    - template: sign-files.yml
      parameters:
        Include: "*.cat"
        WorkingDir: $(Build.BinariesDirectory)\index
        SigningCertificate: ${{ parameters.SigningCertificate }}

    - publish: $(Build.BinariesDirectory)\index
      artifact: index
      displayName: Publish index artifact

    - powershell: |
        git clone https://github.com/python/cpython-bin-deps --revision 9f9e6fc31a55406ee5ff0198ea47bbb445eeb942 --depth 1 --progress -v "putty"
        "##vso[task.prependpath]$(gi putty)"
      workingDirectory: $(Pipeline.Workspace)
      displayName: 'Download PuTTY binaries'

    - ${{ if and(eq(parameters.Publish, 'true'), eq(parameters.SigningCertificate, 'PythonSoftwareFoundation'), eq(variables['Build.SourceBranchName'], 'main')) }}:
      - task: DownloadSecureFile@1
        name: sshkey
        inputs:
          secureFile: pydotorg-ssh.ppk
        displayName: 'Download PuTTY key'

      - powershell: |
          python ci\upload.py
        displayName: 'Publish packages'
        env:
          UPLOAD_URL: $(PyDotOrgUrlPrefix)python/
          UPLOAD_DIR: $(Build.BinariesDirectory)\index
          UPLOAD_URL_PREFIX: $(PyDotOrgUrlPrefix)
          UPLOAD_PATH_PREFIX: $(PyDotOrgUploadPathPrefix)
          UPLOAD_HOST: $(PyDotOrgServer)
          UPLOAD_HOST_KEY: $(PyDotOrgHostKey)
          UPLOAD_USER: $(PyDotOrgUsername)
          UPLOADING_INDEX: true
          UPLOAD_KEYFILE: $(sshkey.secureFilePath)

    - ${{ else }}:
      - powershell: |
          python ci\upload.py
        displayName: 'Pretend to publish packages'
        env:
          UPLOAD_URL: $(PyDotOrgUrlPrefix)python/
          UPLOAD_DIR: $(Build.BinariesDirectory)\index
          UPLOAD_URL_PREFIX: $(PyDotOrgUrlPrefix)
          UPLOAD_PATH_PREFIX: $(PyDotOrgUploadPathPrefix)
          UPLOADING_INDEX: true
          NO_UPLOAD: 1
